# Generated by Django 3.2.14 on 2023-03-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='Gallery')),
            ],
        ),
    ]
