# Generated by Django 3.2.14 on 2023-03-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('news', models.CharField(max_length=2000)),
                ('news_image', models.FileField(upload_to='news_image')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
