# Generated by Django 3.2.8 on 2022-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('Package_id', models.AutoField(primary_key=True, serialize=False)),
                ('Package_duration', models.CharField(max_length=500)),
                ('Package_foodstatus', models.CharField(max_length=500)),
                ('Package_destination', models.CharField(max_length=100)),
                ('Package_destination_id', models.CharField(max_length=100)),
                ('Package_discription', models.CharField(max_length=1000)),
                ('Package_Transpotation_status', models.CharField(max_length=500)),
            ],
        ),
    ]
