# Generated by Django 3.2.8 on 2022-06-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='Package_price',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
