# Generated by Django 3.2.8 on 2022-06-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPackage',
            fields=[
                ('Bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('Package_id', models.CharField(max_length=100)),
                ('Destination_id', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=200)),
                ('Number_of_Gusts', models.CharField(max_length=100)),
                ('Number_of_Gusts_below5', models.CharField(max_length=100, null=True)),
                ('Address_House', models.CharField(max_length=300)),
                ('Locality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('trip_start_date', models.DateField()),
                ('additional_request', models.CharField(max_length=500)),
                ('customer_feedback', models.CharField(max_length=500)),
                ('Payment_status', models.CharField(max_length=100, null=True)),
                ('approval_status', models.BooleanField(null=True)),
            ],
        ),
    ]
