# Generated by Django 3.2.14 on 2022-07-16 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPackage',
            fields=[
                ('Bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('Package_id', models.CharField(max_length=100)),
                ('Destination_id', models.CharField(max_length=100, null=True)),
                ('Name', models.CharField(max_length=200)),
                ('Number_of_Gusts', models.CharField(max_length=100)),
                ('Number_of_Gusts_below5', models.CharField(max_length=100, null=True)),
                ('Address_House', models.CharField(max_length=300)),
                ('Locality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('trip_start_date', models.DateField()),
                ('additional_request', models.CharField(max_length=500, null=True)),
                ('customer_feedback', models.CharField(max_length=500, null=True)),
                ('Payment_amount', models.FloatField(max_length=100)),
                ('Payment_status', models.BooleanField(null=True)),
                ('approval_status', models.BooleanField(null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
