# Generated by Django 3.0.5 on 2022-07-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpackage',
            name='Payment_amount',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
