# Generated by Django 3.0.5 on 2022-07-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingpackage_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpackage',
            name='customer_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
