# Generated by Django 3.2.8 on 2022-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination_List',
            fields=[
                ('Destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('Destination_Name', models.CharField(max_length=100)),
                ('Destination_discription', models.CharField(max_length=1000)),
                ('Destination_image', models.ImageField(upload_to='Destination_image')),
            ],
        ),
    ]
