# Generated by Django 3.2.8 on 2022-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_list',
            name='Destination_contry',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination_list',
            name='Destination_state',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
